# Generated by Django 5.1.5 on 2025-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="location")),
                ("time", models.TimeField(verbose_name="start time")),
                ("action", models.CharField(max_length=255, verbose_name="action")),
                (
                    "is_enjoyable",
                    models.BooleanField(default=False, verbose_name="is enjoyable"),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        default=1,
                        verbose_name="frequency (in days, 1 = daily, 2 = every 2 days, not more than 7 days)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="reward"
                    ),
                ),
                (
                    "time_required",
                    models.IntegerField(
                        verbose_name="required time (in seconds, maximum 120)"
                    ),
                ),
                (
                    "last_completed",
                    models.DateField(
                        blank=True, null=True, verbose_name="last completed"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="is public"),
                ),
            ],
            options={
                "verbose_name": "habit",
                "verbose_name_plural": "habits",
                "ordering": ("id",),
            },
        ),
    ]
